version: "2"
linters:
  default: standard
  enable:
    - gocyclo
    - funlen
    - nestif
    - errorlint
    - unparam
  settings:
    gocyclo:
      min-complexity: 18
    funlen:
      lines: 150
      statements: -1
    nestif:
      min-complexity: 4
  exclusions:
    generated: strict
    paths:
      - internal/gen
      - internal/storage/gen
formatters:
  enable:
    - gofmt
